name: Build VulkanMod for Mali-G77

on:
  push:
    branches: [ dev, main, "Mali-G77*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test --stacktrace --no-daemon
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VulkanMod-1.21.10-Mali-G77
          path: |
            **/build/libs/*.jar
            !**/build/libs/*-sources.jar
          if-no-files-found: warn
